### ISSUE TITLE
When mailling attendees in event, user can remove recipients in opened mail composer

### ISSUE THREAD

**Issue by renaudboyer** [linagora/esn-frontend-calendar#533]
When clicking on "Mail to Attendee" button, it opens a mail composer with event attendee as recipient.

User cannot remove recipient from "To" fields.

![image](https://user-images.githubusercontent.com/13099240/115233209-ea2bf080-a117-11eb-8649-bf211a51bd13.png)

How to reproduce:

* Open an event with attendees
* Click on "Mail to attendee" button
* The mail composer opens
* Recipients are grayed and it's impossible to remove them

**Comment by alagane** [comment]
Cannot reproduce
