### ISSUE TITLE
Updating participation on newly received event from quickview fails to update the event state in the fullcalendar view

### ISSUE THREAD

**Issue by chamerling** [linagora/esn-frontend-calendar#543]
The event quickview is f*****g awesome, anyway I faced an issue:

1. Open the calendar, there is one event waiting for my participation
2. Open the event quickview
3. Set my participation

The quickview participation is updated; Anyway, the fullcalendar event stays the same.

I tried to change the participation from the quickview on other events, without any issue. Maybe this bug is related to the initial state, or maybe it was random Webscoket connection issue, or angular digest issue, ...

**Comment by asmaNode** [comment]
This bug  is not reproducible , i guess it was a websocket conenction issue 
https://streamable.com/4dzh0z
