### ISSUE TITLE
A long calendar name is displayed fully in the selectbox

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-calendar#560]
# Actual Result
A long calendar name is fully displayed, which stretches the select box to the whole page.
![image](https://user-images.githubusercontent.com/69950655/119080103-acc2c780-ba23-11eb-93d0-2beb55b1aad3.png)

# Expected Result
Should display only a part of the long calendar name (for example limit to 30 characters). The rest part should be implied by a 3 dots 

# Environment
DEV platform

**Comment by asmaNode** [comment]
it is not necessary to divide the text we can draw inspiration from the experience of google calendar

**Comment by fabienmoyon** [comment]
Hello, why limit that ? Be able to read all the name of the calendar is well
