### ISSUE TITLE
User Feedback > Calendar email cannot display the bluebar for Microsoft event

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-calendar#581]
# Precondition
The Microsoft user invites OpenPaas user to an event created on Teams. 

# Actual Result
On OpenPaas inbox, the invitation email cannot display event details on the bluebar
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/ed5315e8-d85c-4d7a-9541-076c0419f03d)
EML: [https://app.zenhub.com/files/276895569/e1979853-cb15-4c70-9641-4ea1be7edfca/download](https://app.zenhub.com/files/276895569/e1979853-cb15-4c70-9641-4ea1be7edfca/download)

# Expected Result
The event details from Teams should be able to display on OpenPaas email. 

# Environment 
Production

**Comment by chibenwa** [comment]
Cc @Arsnael 

Can you check the ical can be parsed by ical4j?

**Comment by Arsnael** [comment]
I know close to nothing about ical and I don't consider that as a priority issue atm, but if I get a moment I will check

**Comment by Arsnael** [comment]
@chibenwa

When I check the eml, it looks like a normal text/calendar attachment in base64... When looking at James code it should work. Not sure how to check/test that more deeply though

**Comment by Arsnael** [comment]
or do we miss maybe a step in the prod LNG pipeline?

In preprod, before the ical pipeline, I see this:
```
<mailet match="All" class="org.apache.james.jmap.mailet.TextCalendarBodyToAttachment"/>
```

But it's not there in LNG conf. Should we add it @chibenwa ?

**Comment by chibenwa** [comment]
> <mailet match="All" class="org.apache.james.jmap.mailet.TextCalendarBodyToAttachment"/>
> Should we add it @chibenwa ?

Yes sure we can try.

**Comment by tlle14** [comment]
Retest pass!
Thank guys!
![image](https://user-images.githubusercontent.com/69950655/124218148-dba08300-db23-11eb-8f5a-c3d1b256b9df.png)
