### ISSUE TITLE
Cannot import the ics file successfully

### ISSUE THREAD

**Issue by tlle14** [linagora/esn-frontend-calendar#583]
# Precondition
Has a .ics file. Please download the .ics file here in Ludovic's feedback
https://beta.twake.app/client/9eTCfTnm6fnun7f2xNcyRS/c/tTh8x1X6D5baacWUejdkfb?m=pgHrPS7fMaCciDpoQL7QJg

# Actual Result
After import the .ics file to the calendar, SOMETIMES, there is nothing happened.
Sometimes it works. (with another ics file)

# Expected Result
The import process should be successful.

# Environment
Production

**Comment by asmaNode** [comment]
this is not a bug , the feature of import is not implemented yet
