### ISSUE TITLE
Wrong link to mail when sending email to attendee.

### ISSUE THREAD

**Issue by renaudboyer** [linagora/esn-frontend-calendar#585]
In event form, when clicking on mail to attendee, mailto link is broken.

![image](https://user-images.githubusercontent.com/13099240/123229609-c188f400-d4d6-11eb-865a-5323259aea97.png)

TODO

Make mailto URL configurable in openpaas.js

Similar to https://github.com/linagora/esn-frontend-common-libs/issues/204

**Comment by asmaNode** [comment]
https://github.com/linagora/esn-frontend-mailto-handler/pull/13/
